FROM node:alpine as ui-build

WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY ./ /app/
ARG configuration=production

RUN npm run build -- --output-path=./dist/out --configuration $configuration

FROM nginx:latest
COPY --from=ui-build /app/dist/out/ /usr/share/nginx/html
# Expose port 80
EXPOSE 80
